FROM nvcr.io/nvidia/pytorch:23.12-py3

WORKDIR /
RUN mkdir /work
WORKDIR /work

RUN pip install -U pip && \
    pip install \
        jupyterlab japanize-matplotlib lckr-jupyterlab-variableinspector jupyterlab_nvdashboard tensorboard witwidget

#DL
#RUN pip install install torch torchvision torchaudio

RUN pip install --upgrade "jax[cuda12_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html

#bayes
RUN pip install \
        pymc pymc-marketing bambi arviz orbit-ml lightweight_mmm numpyro blackjax bridgestan[stan] nutpie[stan] dowhy tensorflow-probability 

RUN pip install \
        scikit-learn polars witwidget xgboost lightgbm seaborn statsmodels optuna mlxtend

RUN pip install \
        dask-cuda dask-labextension==6.2.0 bokeh==2.4.2


