FROM tensorflow/tensorflow:2.13.0-gpu-jupyter 
# pyhon3.8

WORKDIR /
RUN mkdir /work
WORKDIR /work

RUN pip install -U pip && \
    pip install \
        japanize-matplotlib lckr-jupyterlab-variableinspector jupyterlab_nvdashboard graphviz

RUN pip install \
        scikit-learn tfx tfx-addons tensorflow-probability tensorflow-model-analysis witwidget xgboost 

RUN pip install "arviz[all]" "dask_labextension<5"

