version: "3.7"
services:
  jupyter_torch_gpu:
    build:
        context: .
        dockerfile: jupyter.dockerfile
    working_dir: /work/
    #runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    #environment:
    #  - NVIDIA_VISIBLE_DEVICES=all
    ports:
        - 8888:8888
        - 8787:8787 
        - 8786:8786
    #    - 6006:6006
    #command: "jupyter lab --port 9911 --ip=0.0.0.0 --allow-root --LabApp.token=''"
    #command: "tensorboard --logdir=/work/dir_tensorboard --port 6006 --host 0.0.0.0"
    command: "jupyter lab --ip=0.0.0.0 --allow-root --LabApp.token=''"
    container_name: jupyter_torch_gpu
    restart: always
    #mem_limit: 54g

  tensorboard:
    build:
        context: .
        dockerfile: tensorboard.dockerfile
    working_dir: /work/
    ports:
        - 6006:6006
    

